dataExtract
bikeSharePredictCTree
bikeSharePredictKNN
bikeSharePredictSVM
bikeSharePredictTBRF
bikeSharePredictTreeBagger
ClassifierApp_CTree
ClassifierApp_EnsTB
RunEnsemble
RunEnsembleSplitCriterion
RunEnsembleRotationForest
RunEnsembleRotationForestWithSplitCriterion

bikeSharePredictSVR
bikeSharePredictTBOptNTrees
bikeSharePredictTBOptPred
RunEnsembleRotationForestAll